# This is not really being used for now, except to define the build process.

[build-system]
requires = ["setuptools >= 75.0.0"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
environment-pass = ["MQ_FILE_PATH"]
# We enable all builds and then cherry-pick the platforms via the `build`
# configuration below.
enable = ["all"]
# See https://cibuildwheel.pypa.io/en/stable/options/#build-skip
# Not sure why it was failing on PyPy 3.11.
build = "cp39-manylinux_x86_64 cp39-win_amd64"
