[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "mqcredist"
version = "9.4.4.0"
description = "IBM MQ C library, distributed as wheels"
maintainers = [
  {name = "Adi Roiban", email = "adiroiban@gmail.com"},
]
requires-python = ">= 3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
license = "LicenseRef-IBM-MQ-C-Redist"
license-files = ['LICENSE.txt']
[project.urls]
Homepage = "https://github.com/ibm-messaging/mq-mqi-python"

[options]
packages = "find:"

[tool.cibuildwheel]
environment-pass = ["MQ_FILE_PATH"]
environment = "LD_LIBRARY_PATH='/project/ibm-mq-c/lib64;/project/ibm-mq-c/gskit9/lib64/'"
# We enable all builds and then cherry-pick the platforms via the `build`
# configuration below.
enable = ["all"]
# See https://cibuildwheel.pypa.io/en/stable/options/#build-skip
# Not sure why it was failing on PyPy 3.11.
build = "cp39-manylinux_x86_64 cp39-win_amd64"
