[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "mqcredist"
version = "9.4.4.0"
description = "IBM MQ C library, distributed as wheels"
maintainers = [
  {name = "Adi Roiban", email = "adiroiban@gmail.com"},
]
requires-python = ">= 3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
license = "LicenseRef-IBM-MQ-C-Redist"
license-files = ['LICENSE.txt']
[project.urls]
Homepage = "https://github.com/ibm-messaging/mq-mqi-python"

[options]
packages = "find:"
